"""empty message

Revision ID: 09ff3a76aaa3
Revises: 91bffe38a96b
Create Date: 2022-01-27 16:49:33.034583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ff3a76aaa3'
down_revision = '91bffe38a96b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reportes', sa.Column('excel', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reportes', 'excel')
    # ### end Alembic commands ###
