"""empty message

Revision ID: 91bffe38a96b
Revises: 
Create Date: 2022-01-21 17:55:50.988720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91bffe38a96b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reporte_lineas_tanque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_reporte', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('escrito_en', sa.DateTime(), nullable=True),
    sa.Column('escrito_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['id_reporte'], ['reportes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reporte_lineas_tanque_id_producto'), 'reporte_lineas_tanque', ['id_producto'], unique=False)
    op.create_index(op.f('ix_reporte_lineas_tanque_id_reporte'), 'reporte_lineas_tanque', ['id_reporte'], unique=False)
    op.add_column('reporte_lineas_compras', sa.Column('volumenUtil', sa.Float(), nullable=True))
    op.add_column('reporte_lineas_compras', sa.Column('volumenFondaje', sa.Float(), nullable=True))
    op.add_column('reporte_lineas_compras', sa.Column('volumenAgua', sa.Float(), nullable=True))
    op.add_column('reporte_lineas_compras', sa.Column('volumenExtraccion', sa.Float(), nullable=True))
    op.add_column('reporte_lineas_compras', sa.Column('temperatura', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reporte_lineas_compras', 'temperatura')
    op.drop_column('reporte_lineas_compras', 'volumenExtraccion')
    op.drop_column('reporte_lineas_compras', 'volumenAgua')
    op.drop_column('reporte_lineas_compras', 'volumenFondaje')
    op.drop_column('reporte_lineas_compras', 'volumenUtil')
    op.drop_index(op.f('ix_reporte_lineas_tanque_id_reporte'), table_name='reporte_lineas_tanque')
    op.drop_index(op.f('ix_reporte_lineas_tanque_id_producto'), table_name='reporte_lineas_tanque')
    op.drop_table('reporte_lineas_tanque')
    # ### end Alembic commands ###
