"""empty message

Revision ID: b166237955c8
Revises: 09ff3a76aaa3
Create Date: 2022-02-21 14:25:19.466589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b166237955c8'
down_revision = '09ff3a76aaa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reportes', sa.Column('dispensarios', sa.Integer(), nullable=True))
    op.add_column('reportes', sa.Column('mangueras', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reportes', 'mangueras')
    op.drop_column('reportes', 'dispensarios')
    # ### end Alembic commands ###
