"""empty message

Revision ID: bae67f142a4d
Revises: 
Create Date: 2023-09-05 17:39:59.945590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae67f142a4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('escrito_en', sa.DateTime(), nullable=True),
    sa.Column('escrito_por', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('nombre_corto', sa.String(length=30), nullable=False),
    sa.Column('claveProducto', sa.String(length=2), nullable=False),
    sa.Column('claveSubProducto', sa.String(length=1), nullable=False),
    sa.Column('composicionOctanajeDeGasolina', sa.String(length=2), nullable=True),
    sa.Column('gasolinaConEtanol', sa.String(length=2), nullable=True),
    sa.Column('claveProductoPEMEX', sa.String(length=30), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('escrito_en', sa.DateTime(), nullable=True),
    sa.Column('escrito_por', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claveProductoPEMEX'),
    sa.UniqueConstraint('claveSubProducto'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('nombre_corto')
    )
    op.create_table('versiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('escrito_en', sa.DateTime(), nullable=True),
    sa.Column('escrito_por', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('zonas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('escrito_en', sa.DateTime(), nullable=True),
    sa.Column('escrito_por', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('rfc', sa.String(length=30), nullable=False),
    sa.Column('rfcProveedorSW', sa.String(length=30), nullable=False),
    sa.Column('id_version', sa.Integer(), nullable=True),
    sa.Column('ftp_on', sa.Boolean(), nullable=True),
    sa.Column('ftp_host', sa.String(length=30), nullable=False),
    sa.Column('ftp_port', sa.String(length=30), nullable=False),
    sa.Column('ftp_username', sa.String(length=30), nullable=False),
    sa.Column('ftp_password', sa.String(length=30), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('escrito_en', sa.DateTime(), nullable=True),
    sa.Column('escrito_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_version'], ['versiones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('rfc')
    )
    op.create_index(op.f('ix_empresas_id_version'), 'empresas', ['id_version'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('id_grupo', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('escrito_en', sa.DateTime(), nullable=True),
    sa.Column('escrito_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_grupo'], ['grupos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id_grupo'), 'usuarios', ['id_grupo'], unique=False)
    op.create_table('estaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('id_zona', sa.Integer(), nullable=True),
    sa.Column('numeroPermisoCRE', sa.String(length=30), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('ruta', sa.String(length=100), nullable=False),
    sa.Column('claveClientePEMEX', sa.String(length=30), nullable=False),
    sa.Column('claveEstacionServicio', sa.String(length=30), nullable=False),
    sa.Column('key_file_path', sa.String(length=255), nullable=True),
    sa.Column('cer_file_path', sa.String(length=255), nullable=True),
    sa.Column('pem_file_path', sa.String(length=255), nullable=True),
    sa.Column('noCertificado', sa.String(length=255), nullable=True),
    sa.Column('certificado_value', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('escrito_en', sa.DateTime(), nullable=True),
    sa.Column('escrito_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['id_zona'], ['zonas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claveClientePEMEX'),
    sa.UniqueConstraint('claveEstacionServicio'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('numeroPermisoCRE')
    )
    op.create_index(op.f('ix_estaciones_id_empresa'), 'estaciones', ['id_empresa'], unique=False)
    op.create_index(op.f('ix_estaciones_id_zona'), 'estaciones', ['id_zona'], unique=False)
    op.create_table('dispensario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numeroDispensario', sa.String(length=2), nullable=False),
    sa.Column('id_estacion', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('escrito_en', sa.DateTime(), nullable=True),
    sa.Column('escrito_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_estacion'], ['estaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numeroDispensario')
    )
    op.create_index(op.f('ix_dispensario_id_estacion'), 'dispensario', ['id_estacion'], unique=False)
    op.create_table('estaciones_productos',
    sa.Column('estacion_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estacion_id'], ['estaciones.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('estacion_id', 'producto_id')
    )
    op.create_table('reportes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_estacion', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('excel', sa.Text(), nullable=True),
    sa.Column('dispensarios', sa.Integer(), nullable=True),
    sa.Column('mangueras', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('escrito_en', sa.DateTime(), nullable=True),
    sa.Column('escrito_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_estacion'], ['estaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reportes_id_estacion'), 'reportes', ['id_estacion'], unique=False)
    op.create_table('tanques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_estacion', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('no_tanque', sa.Integer(), nullable=True),
    sa.Column('volumenUtil', sa.Integer(), nullable=True),
    sa.Column('volumenFondaje', sa.Integer(), nullable=True),
    sa.Column('volumenAgua', sa.Integer(), nullable=True),
    sa.Column('volumenDisponible', sa.Integer(), nullable=True),
    sa.Column('volumenExtraccion', sa.Integer(), nullable=True),
    sa.Column('volumenRecepcion', sa.Integer(), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_reporte', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('escrito_en', sa.DateTime(), nullable=True),
    sa.Column('escrito_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_estacion'], ['estaciones.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tanques_id_estacion'), 'tanques', ['id_estacion'], unique=False)
    op.create_index(op.f('ix_tanques_id_producto'), 'tanques', ['id_producto'], unique=False)
    op.create_table('manguera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identificadorManguera', sa.String(length=1), nullable=False),
    sa.Column('id_Dispensario', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('escrito_en', sa.DateTime(), nullable=True),
    sa.Column('escrito_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_Dispensario'], ['dispensario.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manguera_id_Dispensario'), 'manguera', ['id_Dispensario'], unique=False)
    op.create_index(op.f('ix_manguera_id_producto'), 'manguera', ['id_producto'], unique=False)
    op.create_table('reporte_lineas_compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_reporte', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('numeroTanque', sa.String(length=2), nullable=True),
    sa.Column('volumenUtil', sa.Float(), nullable=True),
    sa.Column('volumenFondaje', sa.Float(), nullable=True),
    sa.Column('volumenAgua', sa.Float(), nullable=True),
    sa.Column('volumenDisponible', sa.Float(), nullable=True),
    sa.Column('volumenExtraccion', sa.Float(), nullable=True),
    sa.Column('volumenRecepcion', sa.Float(), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('capacidadTotalTanque', sa.Float(), nullable=True),
    sa.Column('capacidadOperativaTanque', sa.Float(), nullable=True),
    sa.Column('capacidadUtilTanque', sa.Float(), nullable=True),
    sa.Column('capacidadFondajeTanque', sa.Float(), nullable=True),
    sa.Column('volumenMinimoOperacion', sa.Float(), nullable=True),
    sa.Column('estadoTanque', sa.String(length=1), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('escrito_en', sa.DateTime(), nullable=True),
    sa.Column('escrito_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['id_reporte'], ['reportes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reporte_lineas_compras_id_producto'), 'reporte_lineas_compras', ['id_producto'], unique=False)
    op.create_index(op.f('ix_reporte_lineas_compras_id_reporte'), 'reporte_lineas_compras', ['id_reporte'], unique=False)
    op.create_table('reporte_lineas_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_reporte', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('numeroTotalRegistrosDetalle', sa.Integer(), nullable=False),
    sa.Column('numeroDispensario', sa.String(length=2), nullable=True),
    sa.Column('identificadorManguera', sa.String(length=1), nullable=True),
    sa.Column('sumatoriaVolumenDespachado', sa.Float(), nullable=True),
    sa.Column('sumatoriaVentas', sa.Float(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('escrito_en', sa.DateTime(), nullable=True),
    sa.Column('escrito_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['id_reporte'], ['reportes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reporte_lineas_venta_id_producto'), 'reporte_lineas_venta', ['id_producto'], unique=False)
    op.create_index(op.f('ix_reporte_lineas_venta_id_reporte'), 'reporte_lineas_venta', ['id_reporte'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reporte_lineas_venta_id_reporte'), table_name='reporte_lineas_venta')
    op.drop_index(op.f('ix_reporte_lineas_venta_id_producto'), table_name='reporte_lineas_venta')
    op.drop_table('reporte_lineas_venta')
    op.drop_index(op.f('ix_reporte_lineas_compras_id_reporte'), table_name='reporte_lineas_compras')
    op.drop_index(op.f('ix_reporte_lineas_compras_id_producto'), table_name='reporte_lineas_compras')
    op.drop_table('reporte_lineas_compras')
    op.drop_index(op.f('ix_manguera_id_producto'), table_name='manguera')
    op.drop_index(op.f('ix_manguera_id_Dispensario'), table_name='manguera')
    op.drop_table('manguera')
    op.drop_index(op.f('ix_tanques_id_producto'), table_name='tanques')
    op.drop_index(op.f('ix_tanques_id_estacion'), table_name='tanques')
    op.drop_table('tanques')
    op.drop_index(op.f('ix_reportes_id_estacion'), table_name='reportes')
    op.drop_table('reportes')
    op.drop_table('estaciones_productos')
    op.drop_index(op.f('ix_dispensario_id_estacion'), table_name='dispensario')
    op.drop_table('dispensario')
    op.drop_index(op.f('ix_estaciones_id_zona'), table_name='estaciones')
    op.drop_index(op.f('ix_estaciones_id_empresa'), table_name='estaciones')
    op.drop_table('estaciones')
    op.drop_index(op.f('ix_usuarios_id_grupo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_empresas_id_version'), table_name='empresas')
    op.drop_table('empresas')
    op.drop_table('zonas')
    op.drop_table('versiones')
    op.drop_table('productos')
    op.drop_table('grupos')
    # ### end Alembic commands ###
